# notebooks原始設定全部 map 到四大類
CATEGORY_MAPPING = {
    # Billing
    'Billing': 'Billing',
    'Payment': 'Billing',
    'Finance': 'Billing',
    'Refund': 'Billing',
    'Pricing': 'Billing',
    'Return': 'Billing',
    
    # Technical
    'Technical': 'Technical',
    'Tech Support': 'Technical',
    'Technical Support': 'Technical',
    'IT': 'Technical',
    'Network': 'Technical',
    'Server': 'Technical',
    'Hardware': 'Technical',
    'Software': 'Technical',
    'Software Support': 'Technical',
    'Configuration': 'Technical',
    'Crash': 'Technical',
    'Bug': 'Technical',
    'Outage': 'Technical',
    'Disruption': 'Technical',
    'Troubleshooting': 'Technical',
    'Connectivity': 'Technical',
    'Database': 'Technical',
    'Analytics': 'Technical',
    'Data': 'Technical',
    'API': 'Technical',
    'API Integration': 'Technical',
    'Integration': 'Technical',
    'Display': 'Technical',
    'Performance': 'Technical',
    'Performance,Disruption,Outage,Monitoring,Analysis': 'Technical',
    'Performance,Disruption,IT,Tech Support': 'Technical',
    'Security': 'Technical',
    'Security,IT,Tech Support': 'Technical',
    'Security,IT,Tech Support,Data Privacy,Regulation,Patient Data,Threat Prevention': 'Technical',
    'Security,Outage,Disruption,Recovery,IT,Tech Support': 'Technical',
    'Server': 'Technical',
    'Software Conflict': 'Technical',
    'ERP': 'Technical',
    
    # Account
    'Account': 'Account',
    'Login': 'Account',
    'Customer': 'Account',
    'Customer Service': 'Account',
    'Support': 'Account',
    'HR': 'Account',
    'Employee': 'Account',

    # General (其他全部歸這類)
    'Product': 'General',
    'Feature': 'General',
    'Inquiry': 'General',
    'Marketing': 'General',
    'Documentation': 'General',
    'Organization': 'General',
    'Feedback': 'General',
    'Compliance': 'General',
    'Maintenance': 'General',
    'Sales': 'General',
    'Alert': 'General',
    'Smart Home': 'General',
    'Process Improvement': 'General',
    'Strategy': 'General',
    'Project': 'General',
    'Project Management': 'General',
    'Training': 'General',
    'Audio': 'General',
    'Lead': 'General',
    'Access': 'General',
    'Delivery': 'General',
    'Urgency': 'General',
    'Functionality': 'General',
    'Health': 'General',
    'Customer Support': 'General',
    'Technical Support': 'Technical',  # 特殊有時候混
    'Salesforce': 'Technical'
}