version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

  java-api:
    build:
      context: ./java/wp/ai-ticket
      dockerfile: Dockerfile
    container_name: java-api
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    networks:
      - app-network
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt-frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_API_INTERNAL_URL=http://java-api:8080
      - 'NITRO_ROUTE_RULES__api____proxy=http://java-api:8080/**'
    depends_on:
      - java-api
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge