services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - java-api
      - fastapi
    networks:
      - app-network

  fastapi:
    build:
      context: ../llm
      dockerfile: api/Dockerfile
    container_name: fastapi
    ports:
        - "8000:8000"    #測試用
    environment:
      - TZ=Asia/Taipei
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - "5432:5432"    #測試用
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Asia/Taipei
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../DB:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  java-api:
    build:
      context: ../java/wp/ai-ticket
      dockerfile: Dockerfile
    container_name: java-api
    environment:
      - JAVA_TOOL_OPTIONS=-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Duser.timezone=Asia/Taipei
      - TZ=Asia/Taipei
    env_file:
      - .env
    depends_on:
      fastapi:
        condition: service_started
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy 
    networks:
      - app-network
      
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - TZ=Asia/Taipei
    networks:
      - app-network
      
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - app-network
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - TZ=Asia/Taipei
    ports:
      - "15672:15672"    # 管理介面（對外，開發用）
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400    

volumes:
  postgres_data: